#!/usr/bin/perl -w
use strict;
use Switch;

my $loc;

print "directory: ";
chomp ($loc = <>);

my $info = "$loc/info.txt";
my $outfile = "$loc/index.html";

my @pics = glob("$loc/*.jpg");

my $count = $#pics+1;

print "found $count jpgs; printed to $outfile\n";

open IN, $info;
my @info = <IN>;

my ($title, $date, $about, $bg, $font, $size);

$bg   = "black";
$font = "white";

foreach (@info) {
	switch ($_){
		case /^title/ {
			my @t = split /:/, $_;
			chomp($title = $t[1]);
		}
		case /^date/ {
			my @d = split /:/, $_;
			chomp($date = $d[1]);
		}
		case /^about/ {
			my @a = split /:/, $_;
			chomp($about = $a[1]);
		}
		case /^color/ {
			my @c = split /:/, $_;
			if ($c[1] == 0) {
				$bg = "black";
				$font = "white";
			} else {
				$bg = "white";
				$font = "black";
			}
		}

		case /^size/ {
			my @s = split /:/, $_;
			switch ($s[1]) {
				case /0/ {$size = 200;}
				case /1/ {$size = 800;}
				case /2/ {$size = 1000;}
			}
		}
	}
}

open OUT, ">", $outfile;
select OUT;
print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n";
print "<html>\n";
print "<head>\n";
print "<title>$title</title>\n";
print "<body bgcolor=$bg vlink=#c0c0c0 link=#c0c0c0 text=$font>\n";
print "<center>\n";
print "<p><b>$date</b></p>\n";
print "<p>$about</p>\n";
print "<p>";

foreach (@pics) {
	my @picname = split /\/+/, $_;
	my $pic = pop(@picname);
	print "<img src=\"http://modigsear.cfa.cmu.edu/users/hvincent/photos/$loc/$pic\" border=1 alt=\"$pic\" title=\"http://modigsear.cfa.cmu.edu/users/hvincent/photos/$loc/$pic\">\n";
}

print "</p>";

print "<p>vincent zeng (hvincent at <a href=\"http://modgethanc.com\">modgethancdotcom</a>)</p>\n";
print "</center></body></html>";

close OUT;
